# Generated by Django 3.2.9 on 2021-11-30 21:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(default=12345, max_length=5)),
                ('numero_conta', models.UUIDField(default=uuid.uuid4)),
                ('saldo_inicial', models.PositiveIntegerField(default=500)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastro')),
            ],
        ),
    ]
