# Generated by Django 3.2.9 on 2021-12-02 02:23

import conta.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(default=12345, max_length=5)),
                ('numero_conta', models.IntegerField(default=conta.models.num_aleatorio, unique=True)),
                ('saldo', models.PositiveIntegerField(default=500)),
                ('cadastro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastro')),
            ],
        ),
    ]
