# Generated by Django 3.2.9 on 2021-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='saldo_inicial',
            new_name='saldo',
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero_conta',
            field=models.IntegerField(unique=True),
        ),
    ]
