# Generated by Django 3.2.9 on 2021-11-30 22:02

import conta.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_endereço_cadastro_endereco'),
        ('conta', '0002_auto_20211130_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cadastro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastro'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero_conta',
            field=models.IntegerField(default=conta.models.num_aleatorio, unique=True),
        ),
    ]
