# Generated by Django 3.2.9 on 2021-12-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_rename_endereço_cadastro_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_a_ser_transferido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consistencia_dados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_transacao', models.PositiveSmallIntegerField(choices=[(1, 'Depósito'), (2, 'Saque'), (3, 'Cancelar')])),
                ('data_hora_transacao', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia', to='cadastro.cadastro')),
            ],
            options={
                'ordering': ['data_hora_transacao'],
            },
        ),
    ]
