# Generated by Django 3.2.9 on 2021-12-01 19:47

import cadastro.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_nome', models.CharField(default=None, max_length=150, verbose_name=cadastro.models.Cadastro)),
                ('numero_conta_destino', models.IntegerField()),
                ('valor_para_transferencia', models.IntegerField()),
                ('cadastro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastro')),
            ],
        ),
    ]
