# Generated by Django 3.2.9 on 2021-12-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='consistencia_dados',
            new_name='saldo_depois_transacao',
        ),
    ]
