# Generated by Django 3.2.9 on 2021-11-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
