# Generated by Django 3.2.9 on 2021-12-01 21:24

import cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_endereço_cadastro_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=11, validators=[cadastro.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='rg',
            field=models.CharField(max_length=9, validators=[cadastro.models.validate_Rg]),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone_de_contato',
            field=models.CharField(max_length=11, validators=[cadastro.models.validate_telefone_de_contato]),
        ),
    ]
